-- Dummy Contact Messages for EcoConnect
-- Sample inquiries, feedback, and support requests

-- Insert dummy contact messages
INSERT INTO contact_messages (id, name, email, phone, subject, message, category, status, admin_notes, created_at, resolved_at) VALUES
(8001, 'Rahul Sharma', 'rahul.sharma@email.com', '+91-98765-43210', 'Question about recycling schedule', 'Hi, I want to know if the recycling pickup schedule for Sector 137 Noida has changed. Earlier it was every Tuesday but I did not see the truck last week. Please confirm the correct schedule.', 'general', 'resolved', 'Confirmed schedule - Tuesdays 8-10 AM. Notified user about Holiday week delay.', '2025-03-15 10:30:00', '2025-03-16 11:00:00'),
(8002, 'Priya Patel', 'priya.patel@email.com', '+91-98765-12345', 'Issue with points not credited', 'I completed a waste pickup request on March 12th but the 75 green points have not been credited to my account yet. Request ID was somewhere around 1002. Can you please check and credit my points?', 'complaint', 'resolved', 'Verified completion, credited 75 points to user account. User notified via email.', '2025-03-15 14:00:00', '2025-03-16 09:30:00'),
(8003, 'Amit Kumar', 'amit.kumar@email.com', '+91-99887-66554', 'Partnership proposal for corporate waste management', 'I am the facilities manager at a corporate office in Connaught Place with 500+ employees. We are looking for a sustainable waste management partner. Can someone from your team contact me to discuss a corporate plan?', 'partnership', 'in_progress', 'Assigned to BD team. Meeting scheduled for March 25th.', '2025-03-20 11:00:00', NULL),
(8004, 'Sunita Devi', 'sunita.devi@email.com', '+91-98712-34567', 'Suggestion for more collection centers', 'It would be great if you could open a collection center in Sector 21 Faridabad. Currently we have to travel to Sector 15 which is quite far. Many residents in our area are interested in recycling but the distance is a barrier.', 'suggestion', 'resolved', 'Noted for expansion planning. Suggested using home pickup service meanwhile.', '2025-03-18 09:00:00', '2025-03-19 16:00:00'),
(8005, 'Vikram Singh', 'vikram.singh@email.com', '+91-98999-88877', 'App is not loading properly', 'The EcoConnect website is taking too long to load on my mobile browser. I am using Chrome on Android. The dashboard page keeps showing loading spinner. Please fix this technical issue.', 'support', 'in_progress', 'Forwarded to tech team. Requested more details about device model and OS version.', '2025-03-28 10:00:00', NULL),
(8006, 'Meera Gupta', 'meera.gupta@email.com', '+91-98123-45678', 'How to dispose of old medicines?', 'I have a lot of expired medicines at home. Can you tell me how to properly dispose of them? Are they considered hazardous waste? Can I include them in my next hazardous waste pickup request?', 'general', 'resolved', 'Advised on safe medicine disposal. Scheduled special pickup for pharmaceutical waste.', '2025-03-25 14:30:00', '2025-03-26 11:00:00'),
(8007, 'Arjun Reddy', 'arjun.reddy@email.com', '+91-96543-21098', 'Feedback on recent pickup service', 'The pickup team came yesterday and did a great job. They were professional and sorted everything properly. Just wanted to share positive feedback. Keep up the good work!', 'general', 'resolved', 'Positive feedback shared with operations team. User thanked for appreciation.', '2025-03-22 09:00:00', '2025-03-22 12:00:00'),
(8008, 'Neha Verma', 'neha.verma@email.com', '+91-97654-32109', 'Compliant about missed pickup', 'My pickup was scheduled for March 25th morning slot but nobody showed up. This is the second time this has happened. Very disappointed with the service reliability.', 'complaint', 'in_progress', 'Escalated to ops manager. Rescheduled pickup with priority flag. Discount points offered.', '2025-03-26 16:00:00', NULL),
(8009, 'Sanjay Kumar', 'sanjay.kumar@email.com', '+91-95432-10987', 'Account activation issue', 'I registered last week but my account still shows as inactive. I cannot book any services. Can you please activate my account? Email is sanjay.kumar@email.com', 'support', 'resolved', 'Account activated. Verification email was in spam folder. User informed.', '2025-03-24 10:00:00', '2025-03-24 14:00:00'),
(8010, 'Ananya Roy', 'ananya.roy@email.com', '+91-94321-09876', 'Volunteer coordination question', 'As a regular volunteer, I want to know if there is a WhatsApp group or other coordination channel for volunteers. Would be helpful to connect with other volunteers for carpooling to events.', 'general', 'resolved', 'Added user to volunteer WhatsApp group. Shared upcoming event calendar.', '2025-03-10 11:00:00', '2025-03-11 09:00:00'),
(8011, 'Rajesh Khanna', 'rajesh.khanna@email.com', '+91-93210-98765', 'Request for awareness session in our office', 'I am an admin at an office in Sector 21 Faridabad. Would it be possible to arrange a recycling awareness session for our employees? Around 50 people would attend. Please let me know the possibilities.', 'partnership', 'resolved', 'Scheduled awareness workshop for April 15th. Sent confirmation email.', '2025-03-20 13:00:00', '2025-03-22 10:00:00'),
(8012, 'Divya Malhotra', 'divya.malhotra@email.com', '+91-92109-87654', 'Reward redemption not received', 'I redeemed my points for a free pickup service two weeks ago but have not received any confirmation or scheduling. Can you check the status of my redemption ID 6028?', 'complaint', 'in_progress', 'Looking into redemption status. User will be contacted within 24 hours.', '2025-04-03 15:00:00', NULL),
(8013, 'Karan Mehta', 'karan.mehta@email.com', '+91-91098-76543', 'Suggestion for e-waste collection event', 'Can you organize an e-waste collection event specifically for IT companies in Noida? Many offices have old electronics but no easy way to dispose them properly. A weekend collection drive would be very helpful.', 'suggestion', 'in_progress', 'Forwarded to events team. Good idea for Q2 planning.', '2025-03-30 10:00:00', NULL),
(8014, 'Pooja Shah', 'pooja.shah@email.com', '+91-90987-65432', 'Password reset not working', 'I am trying to reset my password but the reset link is not being sent to my email. I checked spam folder as well. Can you help me reset my password manually?', 'support', 'resolved', 'Password reset manually. User advised to check email settings.', '2025-03-26 14:00:00', '2025-03-26 16:00:00'),
(8015, 'Rohit Malhotra', 'rohit.malhotra@email.com', '+91-99876-54321', 'Query about commercial services', 'We are a small startup in Gurugram with 20 employees. What commercial waste management options do you offer for small businesses? Looking for weekly pickup service.', 'general', 'resolved', 'Sent commercial services brochure. Follow-up call scheduled.', '2025-03-18 09:30:00', '2025-03-20 11:00:00'),
(8016, 'Guest User', 'guest.user@email.com', '+91-99999-88888', 'How to join as volunteer?', 'I am interested in volunteering for your tree plantation events. What is the process to register as a volunteer? Are there any requirements or training provided?', 'general', 'resolved', 'Shared volunteer registration link. Invitation sent for upcoming orientation.', '2025-03-28 11:00:00', '2025-03-29 10:00:00'),
(8017, 'Corporate Admin', 'corp.admin@company.com', '+91-97777-77777', 'Bulk dustbin order inquiry', 'We need 100 mixed waste dustbins for our new office building. Can you provide a quote and delivery timeline? Also interested in branded bins with our company logo.', 'partnership', 'in_progress', 'Quote requested from procurement. Design team contacted for branding options.', '2025-04-01 10:00:00', NULL),
(8018, 'Student Representative', 'student@college.edu', '+91-96666-66666', 'College sustainability collaboration', 'We are from an engineering college in Delhi and want to collaborate on a sustainability project. Would EcoConnect be interested in partnering for a semester-long waste management initiative?', 'partnership', 'in_progress', 'Interesting proposal. Academic coordinator will reach out next week.', '2025-04-02 14:00:00', NULL)
ON DUPLICATE KEY UPDATE email = VALUES(email);
